name: Laravel Pint & PHPStan CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Run Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, pcntl

      - name: Install Composer dependencies
        run: composer install --no-progress --no-scripts --prefer-dist

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test --verbose

  analyze:
    name: Run PHPStan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, pcntl

      - name: Install Composer dependencies
        run: composer install --no-progress --no-scripts --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --level=5 --memory-limit=2G
